# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('keyword', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
