# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180226_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
