# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to=project.models.directory),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default='/'),
        ),
    ]
