# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180227_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=' ', max_length=20, primary_key=True, serialize=False),
        ),
    ]
