# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180227_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
