# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180227_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
