# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180227_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='idn',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
