# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20180227_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.CharField(default=' ', max_length=200, primary_key=True),
        ),
    ]
