# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20180227_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
